<?php
// $pageTitle  -> title of the page
// $content    -> HTML of the page (generated by each page)
// Provide safe defaults to avoid undefined variable notices when
// this layout is included without those variables set by the caller.
$pageTitle = isset($pageTitle) ? $pageTitle : 'Back Office';
$content = isset($content) ? $content : '';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $pageTitle ?></title>

    <!-- TEMPLATE CSS -->
    <link rel="stylesheet" href="/projetweb/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/projetweb/assets/css/style.css">
    <link rel="stylesheet" href="/projetweb/assets/css/icons.css">
</head>

<body>

    <!-- SIDEBAR -->
    <div class="sidebar">
        <div class="logo">
            <h2>Back Office</h2>
        </div>
        <ul class="menu">
            <li><a href="listReclamation.php">Reclamations</a></li>
            <li><a href="response.php">Responses</a></li>
        </ul>
    </div>

    <!-- MAIN CONTENT -->
    <div class="main-content">
        <header>
            <h1><?= $pageTitle ?></h1>
        </header>

        <section class="page-content">
            <?= $content ?>
        </section>
    </div>

    <!-- TEMPLATE JS -->
    <script src="/projetweb/assets/js/bootstrap.bundle.min.js"></script>
    <script src="/projetweb/assets/js/main.js"></script>

</body>
</html>
